export const stiPage = {
  en: {
    label: 'Sexual Health',
    labelStyle: { background: 'rgba(230,160,30,0.12)', borderColor: 'rgba(230,160,30,0.3)', color: 'var(--warning)' },
    heroStyle: 'radial-gradient(ellipse at 20% 50%,hsl(38,50%,10%) 0%,transparent 60%),var(--bg-dark)',
    titleAccent: 'STIs',
    titleRest: '& STDs',
    description:
      'Sexually transmitted infections are common and treatable. Knowledge, testing, and prevention protect you and your partners.',
    badges: [
      { icon: 'shield-alt', color: 'var(--primary)', text: 'Prevention Saves Lives' },
      { icon: 'vial', color: 'var(--info)', text: 'Testing is Confidential' },
      { icon: 'lock', color: 'var(--accent)', text: 'No Shame, No Judgment' },
    ],
    nav: [
      { id: 'what', icon: 'virus', label: 'What Are STIs' },
      { id: 'common', icon: 'list-alt', label: 'Common STIs' },
      { id: 'symptoms', icon: 'search', label: 'Symptoms' },
      { id: 'prevention', icon: 'shield-alt', label: 'Prevention' },
      { id: 'testing', icon: 'vial', label: 'Testing & Treatment' },
    ],
    remember:
      'Many STIs have no symptoms. Regular testing is responsible — not shameful. Free HIV testing is available across Rwanda.',
    banner: {
      variant: 'warning',
      icon: 'exclamation-triangle',
      title: 'Important Reminder',
      text: 'Many STIs have no visible symptoms but can still be passed to others and cause serious health problems if untreated. Regular testing is the only way to know your status.',
    },
    sections: [
      {
        id: 'what',
        icon: 'virus',
        title: 'What Are STIs?',
        intro:
          'Sexually Transmitted Infections (STIs), also called STDs, are infections passed primarily through sexual contact — vaginal, anal, or oral sex.',
        info: {
          variant: 'warning',
          icon: 'exchange-alt',
          title: 'How STIs Are Transmitted',
          list: [
            'Unprotected vaginal, anal, or oral sex',
            'Sharing needles or sharp objects',
            'Blood transfusion with infected blood',
            'From mother to child during pregnancy, birth, or breastfeeding',
            'Some STIs (like herpes) spread through skin-to-skin contact',
          ],
        },
      },
      {
        id: 'common',
        icon: 'list-alt',
        title: 'Common STIs',
        stiGrid: [
          { badge: 'VIRAL', badgeStyle: { background: 'rgba(220,30,30,0.15)', color: '#ff6b6b' }, title: 'HIV / AIDS', text: 'Attacks the immune system. No cure, but highly manageable with ART. Prevented with condoms, PrEP, and regular testing.' },
          { badge: 'VIRAL', badgeStyle: { background: 'rgba(230,160,30,0.15)', color: 'var(--warning)' }, title: 'HPV', text: 'Most common STI. Can cause genital warts and cervical cancer. HPV vaccine is available at health centers.' },
          { badge: 'VIRAL', badgeStyle: { background: 'rgba(130,60,200,0.15)', color: 'var(--accent)' }, title: 'Herpes (HSV)', text: 'Causes painful blisters. No cure, but antivirals reduce outbreaks and transmission risk.' },
          { badge: 'BACTERIAL', badgeStyle: { background: 'rgba(30,145,220,0.15)', color: 'var(--info)' }, title: 'Gonorrhea', text: 'Causes discharge and painful urination. Curable with antibiotics if treated early.' },
          { badge: 'BACTERIAL', badgeStyle: { background: 'rgba(26,160,120,0.15)', color: 'var(--primary)' }, title: 'Chlamydia', text: 'Often has NO symptoms. Most common curable STI. Easily treated with antibiotics.' },
          { badge: 'BACTERIAL', badgeStyle: { background: 'rgba(220,80,110,0.15)', color: 'var(--coral)' }, title: 'Syphilis', text: 'Starts with painless sores. Curable with penicillin if caught early.' },
        ],
      },
      {
        id: 'symptoms',
        icon: 'search',
        title: 'Common Signs & Symptoms',
        intro: 'These symptoms may indicate an STI. If you notice any, get tested promptly.',
        dualInfo: [
          {
            variant: 'warning',
            icon: 'users',
            title: 'In Both Men & Women',
            list: ['Unusual discharge', 'Pain or burning when urinating', 'Sores, blisters, or bumps', 'Rash on hands, feet, or body', 'Genital warts', 'Itching or irritation'],
          },
          {
            variant: 'coral',
            icon: 'venus',
            title: 'Additional Signs in Women',
            list: ['Unusual vaginal discharge', 'Bleeding between periods', 'Pain during sex', 'Lower abdominal pain', 'Burning or swelling'],
          },
        ],
        info: {
          variant: 'danger',
          icon: 'info-circle',
          title: 'Remember',
          text: 'Many people with STIs — especially chlamydia and early HIV — have NO symptoms at all. The only way to know for sure is to get tested.',
        },
      },
      {
        id: 'prevention',
        icon: 'shield-alt',
        title: 'How to Prevent STIs',
        preventionGrid: [
          { icon: 'shield-alt', color: 'var(--primary)', title: 'Use Condoms Correctly', text: 'The most effective way to prevent STIs during sex. Use for vaginal, anal, and oral sex.' },
          { icon: 'vial', color: 'var(--info)', title: 'Get Tested Regularly', text: 'If sexually active, get tested at least once a year. Free at Rwanda health centers.' },
          { icon: 'syringe', color: 'var(--accent)', title: 'Get Vaccinated', text: 'HPV vaccine protects against cervical cancer. Available at health centers.' },
          { icon: 'pills', color: 'var(--primary)', title: 'PrEP for HIV', text: 'If at high risk for HIV, take PrEP daily. Very effective when taken consistently.' },
          { icon: 'handshake', color: 'var(--text-primary)', title: 'Communicate with Partners', text: 'Talk openly about testing and protection. Mutual testing builds trust.' },
          { icon: 'ban', color: 'var(--text-primary)', title: 'Avoid Sharing Sharp Items', text: 'Never share needles, razors, or scissors. HIV and hepatitis can spread this way.' },
        ],
      },
      {
        id: 'testing',
        icon: 'vial',
        title: 'Testing and Treatment',
        intro: 'Getting tested is a sign of responsibility. Early treatment protects you and others.',
        info: {
          variant: 'success',
          icon: 'check-circle',
          title: 'What to Do',
          list: [
            'Get tested if you had unprotected sex or have symptoms',
            'HIV and STI tests are free at health centers across Rwanda',
            'Bacterial STIs often clear with a short course of antibiotics',
            'Finish all medication even if you feel better',
            'Tell partner(s) so they can get treated too',
          ],
        },
        info2: {
          variant: 'info',
          icon: 'heart',
          title: 'HIV in Rwanda',
          text: 'Rwanda leads in HIV response: free testing, ART treatment, and programmes to protect babies (PMTCT). Early treatment lets people live long, healthy lives.',
        },
      },
    ],
  },
  rw: {
    label: "Ubuzima bw'imyororokere",
    labelStyle: { background: 'rgba(230,160,30,0.12)', borderColor: 'rgba(230,160,30,0.3)', color: 'var(--warning)' },
    heroStyle: 'radial-gradient(ellipse at 20% 50%,hsl(38,50%,10%) 0%,transparent 60%),var(--bg-dark)',
    titleAccent: 'Indwara',
    titleRest: 'zihurira',
    description: 'Indwara zihurira mu guhunda ziri hose kandi zivurwa. Ubumenyi, gusuzuma, no kwirinda birinda wowe n\'abandi.',
    badges: [
      { icon: 'shield-alt', color: 'var(--primary)', text: 'Kurinda ni ubuzima' },
      { icon: 'vial', color: 'var(--info)', text: 'Gusuzuma ni mu ibanga' },
      { icon: 'lock', color: 'var(--accent)', text: 'Nta gucapwa' },
    ],
    nav: [
      { id: 'what', icon: 'virus', label: 'STI ni iki' },
      { id: 'common', icon: 'list-alt', label: 'STIs zisanzwe' },
      { id: 'symptoms', icon: 'search', label: 'Ibimenyetso' },
      { id: 'prevention', icon: 'shield-alt', label: 'Kurinda' },
      { id: 'testing', icon: 'vial', label: 'Gusuzuma no kuvura' },
    ],
    remember: 'STIs nyinshi ntizigaragaza ibimenyetso. Gusuzuma buri gihe ni inshingano — si isoni. Gusuzuma SIDA ni ubuntu mu Rwanda.',
    banner: {
      variant: 'warning',
      icon: 'exclamation-triangle',
      title: 'Icyitonderwa',
      text: 'STIs nyinshi ntizigaragaza ibimenyetso ariko zishobora gutera abandi. Gusuzuma gusa ni uko wamenya imiterere yawe.',
    },
    sections: [
      {
        id: 'what',
        icon: 'virus',
        title: 'STI / STD ni iki?',
        intro: 'Indwara zihurira mu guhunda zikwirakwira binyuze mu guhunda — mu gitsina, mu gitsina cy\'inyuma, cyangwa mu kanwa.',
        info: {
          variant: 'warning',
          icon: 'exchange-alt',
          title: 'Uko zikwirakwira',
          list: ['Guhunda nta kurinda', 'Gusangira imiheto', 'Kuva ku nyina ku mwana', 'Herpes — kuva ku ruhu'],
        },
      },
      {
        id: 'common',
        icon: 'list-alt',
        title: 'STIs zisanzwe',
        stiGrid: [
          { badge: 'VIRAL', badgeStyle: { background: 'rgba(220,30,30,0.15)', color: '#ff6b6b' }, title: 'SIDA', text: 'Ihungabanya ubudahangarwa. Nta mvura ariko ART ituma abantu babaho neza.' },
          { badge: 'VIRAL', badgeStyle: { background: 'rgba(230,160,30,0.15)', color: 'var(--warning)' }, title: 'HPV', text: 'STI isanzwe cyane. Ishobora gutera kanseri. Hari vaccine.' },
          { badge: 'VIRAL', badgeStyle: { background: 'rgba(130,60,200,0.15)', color: 'var(--accent)' }, title: 'Herpes', text: 'Itera ibisebe. Ivurwa n\'imiti yo kugabanya ibibazo.' },
          { badge: 'BACTERIAL', badgeStyle: { background: 'rgba(30,145,220,0.15)', color: 'var(--info)' }, title: 'Gonorrhea', text: 'Itera amase n\'ububabare. Ivurwa n\'imiti.' },
          { badge: 'BACTERIAL', badgeStyle: { background: 'rgba(26,160,120,0.15)', color: 'var(--primary)' }, title: 'Chlamydia', text: 'Akenshi nta bimenyetso. Ivurwa vuba.' },
          { badge: 'BACTERIAL', badgeStyle: { background: 'rgba(220,80,110,0.15)', color: 'var(--coral)' }, title: 'Syphilis', text: 'Itangira n\'igisebe. Ivurwa n\'penicillin vuba.' },
        ],
      },
      {
        id: 'symptoms',
        icon: 'search',
        title: 'Ibimenyetso',
        intro: 'Niba ubone ibi, gusuzuma vuba ni ngombwa.',
        dualInfo: [
          { variant: 'warning', icon: 'users', title: 'Ku bose', list: ['Amase atari asanzwe', 'Ububabare igihe ushyira', 'Ibisebe', 'Umutwe', 'Guhaha'] },
          { variant: 'coral', icon: 'venus', title: 'Ku bagore', list: ['Amase menshi', 'Amaraso hagati y\'amenzi', 'Ububabare mu guhunda', 'Ububabare mu nda'] },
        ],
        info: { variant: 'danger', icon: 'info-circle', title: 'Ibuka', text: 'Benshi bafite STI ntibagira ibimenyetso. Gusuzuma gusa nibyo bimenya.' },
      },
      {
        id: 'prevention',
        icon: 'shield-alt',
        title: 'Uko wirinda',
        preventionGrid: [
          { icon: 'shield-alt', color: 'var(--primary)', title: 'Koresha ibigabo', text: 'Birinda indwara zihurira.' },
          { icon: 'vial', color: 'var(--info)', title: 'Gusuzuma', text: 'Buri mwaka niba uhangana.' },
          { icon: 'syringe', color: 'var(--accent)', title: 'Vaccine', text: 'HPV irinda kanseri.' },
          { icon: 'pills', color: 'var(--primary)', title: 'PrEP', text: 'Kurinda SIDA ku bafite akaga.' },
          { icon: 'handshake', color: 'var(--text-primary)', title: 'Vugana', text: 'Vugana n\'uwo muhana ku gusuzuma.' },
          { icon: 'ban', color: 'var(--text-primary)', title: 'Ntusangire imiheto', text: 'SIDA na hepatitis zishobora guturuka aho.' },
        ],
      },
      {
        id: 'testing',
        icon: 'vial',
        title: 'Gusuzuma no kuvura',
        intro: 'Gusuzuma ni inshingano. Ubuvuzi vuba birinda wowe n\'abandi.',
        info: {
          variant: 'success',
          icon: 'check-circle',
          title: 'Ibikorwa',
          list: ['Suzuma nyuma yo guhunda nta kurinda', 'Ni ubuntu mu Rwanda', 'Rangiza imiti yose', 'Bwira uwo muhana'],
        },
        info2: { variant: 'info', icon: 'heart', title: 'SIDA mu Rwanda', text: 'Gusuzuma kubuntu, ART, na PMTCT — ubuvuzi vuba butuma abantu babaho neza.' },
      },
    ],
  },
};
